site_name: Documentation Demo for Static rendered HTML Doc
nav:
  - index.md
  - getting_started.md
  - demo_project.md
  - MarkdownExamples.md
  - Enhancements.md
  - Themes.md
  - add/imprint.md
theme: 
    name: material
    language: de
    font: false
    favicon: favicon.png
    logo: logo.png  
extra_css: 
    - css/custom.css
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details